theme: minima
title: Pierre de Malliard
tagline: Personal Website - Pierre de Malliard
author:
  name: Pierre de Malliard
description: ""
logo: profile_picture.jpeg
google_analytics: G-VM93DL0JJ3

minima:
  skin: classic
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: twitter, user_url: "https://twitter.com/PMalliard" }
    - { platform: github,  user_url: "https://github.com/Pidem" }

header_pages: []

plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-feed
