theme: jekyll-theme-minimal
tagline: Personal Website - Pierre de Malliard
author: Pierre de Malliard
title: Pierre de Malliard
logo: profile_picture.jpeg
twitter: 
  username: PMalliard
google_analytics: G-VM93DL0JJ3

plugins:
  - jekyll-seo-tag
  - jemoji
